---
- name: Postgresql
  tags: postgresql
  become: yes
  block:

  - name: Install PGP key
    apt_key:
      url: https://www.postgresql.org/media/keys/ACCC4CF8.asc

  - name: Populate sources list
    shell: echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list

  - name: Install Postgresql
    apt:
      name: postgresql
      update_cache: yes

  - name: Find settings directories
    find:
      paths: /etc/postgresql
      patterns: '*'
      file_type: directory
    register: postgresql_dirs

  - name: Allow local connections with password
    with_items: "{{ postgresql_dirs.files }}"
    lineinfile:
      path: "{{ item.path }}/main/pg_hba.conf"
      regexp: '^local( +)all( +)all( +)peer$'
      line: 'local\1all\2all\3md5'
      backrefs: yes

  - name: Restart postgresql service
    service:
      name: postgresql
      state: restarted
