---
- name: Postgresql
  tags: postgresql
  become: yes
  block:

  - name: Install PGP key
    apt_key:
      url: https://www.postgresql.org/media/keys/ACCC4CF8.asc

  - name: Populate sources list
    shell: echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list

  - name: Install Postgresql
    apt:
      name: postgresql-10
      update_cache: yes
