---
- name: Rust
  tags: rust
  block:

    - name: Download rustup script
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/rustup-init.sh

    - name: Install rust
      script: /tmp/rustup-init.sh -y
