---
- name: Rust
  tags: rust
  block:

    - name: Download rustup script
      shell: curl https://sh.rustup.rs --output /tmp/rustup-init.sh
      args:
        warn: false

    - name: Install rust
      script: /tmp/rustup-init.sh -y

    - name: Update rust
      script: ~/.cargo/bin/rustup update stable
