---
- name: Go Language
  tags: golang
  become: yes
  block:

    - name: Download Go distribution
      shell: curl {{ golang_url }} --output /tmp/{{ golang_dist }}.linux-amd64.tar.gz
      args:
        warn: false

    - name: Remove existing Go installation if any
      file:
        path: /usr/local/go
        state: absent

    - name: Extract Go distribution binaries
      unarchive:
        src: /tmp/{{ golang_dist }}.linux-amd64.tar.gz
        dest: /usr/local/

    - name: Add bin directories to PATH
      copy:
        src: golang-path.sh
        dest: /etc/profile.d/golang-path.sh
