---
- name: Go Language
  tags: golang
  become: yes
  block:

    - name: Fetch Go download page
      uri:
        url: https://golang.org/dl/
        return_content: yes
      register: golang_html

    - name: Discover latest Go distribution filename
      set_fact:
        golang_filename: "{{ golang_html.content | regex_search('go[0-9.]+[.]linux-amd64.tar.gz') }}"

    - name: Download Go distribution
      shell: curl https://dl.google.com/go/{{ golang_filename }} --output /tmp/{{ golang_filename }}
      args:
        warn: false

    - name: Remove existing Go installation if any
      file:
        path: /usr/local/go
        state: absent

    - name: Extract Go distribution binaries
      unarchive:
        src: /tmp/{{ golang_filename }}
        dest: /usr/local/

    - name: Add bin directories to PATH
      copy:
        src: golang-path.sh
        dest: /etc/profile.d/golang-path.sh
