---
- name: Go Language
  tags: golang
  become: yes
  block:

    - name: Fetch Go download page
      uri:
        url: https://golang.org/dl/
        return_content: yes
      register: golang_html

    - name: Discover latest Go download url
      set_fact:
        golang_url: "{{ golang_html.content | regex_search('https://dl.google.com/go/go[0-9.]+.linux-amd64.tar.gz') }}"

    - name: Download Go distribution
      shell: curl {{ golang_url }} --output /tmp/{{ golang_url | basename }}.linux-amd64.tar.gz
      args:
        warn: false

    - name: Remove existing Go installation if any
      file:
        path: /usr/local/go
        state: absent

    - name: Extract Go distribution binaries
      unarchive:
        src: /tmp/{{ golang_url | basename }}.linux-amd64.tar.gz
        dest: /usr/local/

    - name: Add bin directories to PATH
      copy:
        src: golang-path.sh
        dest: /etc/profile.d/golang-path.sh
