---
- name: NodeJS
  tags: nodejs
  become: yes
  block:

    - name: Install node apt signing key
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

    - name: Add node repository to apt sources
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ nodejs_dist }} {{ ansible_distribution_release }} main"
        filename: nodejs
        update_cache: yes

    - name: Install node
      apt:
        name: nodejs
        state: latest

    - name: Upgrade npm
      npm:
        name: npm
        global: yes
        state: latest
