---
- name: NodeJS
  tags: nodejs
  become: yes
  block:

    - name: Install node
      shell: snap install node --classic

    - name: Upgrade npm
      npm:
        name: npm
        global: yes
        state: latest
