---
- name: Python
  tags: python
  block:

    - name: Install dependencies
      become: yes
      apt:
        state: latest
        name:
          - build-essential
          - curl
          - git
          - libc6-dev
          - libffi-dev
          - libgdbm-dev
          - libncursesw5-dev
          - libsqlite3-dev
          - libssl-dev
          - openssl
          - python-dev
          - python-pip
          - python-setuptools
          - python3-dev
          - python3-distutils
          - tk-dev
          - zlib1g-dev

    - name: Check if pyenv is installed for the current user
      register: pyenv
      stat:
        path: ~/.pyenv

    - name: Install pyenv
      shell: curl https://pyenv.run | bash
      when: not pyenv.stat.exists

    - name: Update pyenv
      shell: ~/.pyenv/bin/pyenv update

    - name: Add pyenv lines to bashrc
      blockinfile:
        path: ~/.bashrc
        block: |
          # pyenv
          export PATH="~/.pyenv/bin:$PATH"
          eval "$(pyenv init -)"
          eval "$(pyenv virtualenv-init -)"

    - name: Install pipenv
      pip:
        name: pipenv
        extra_args: --user
        state: latest
