---
- name: Atom
  tags: atom
  become: yes
  block:

    - name: Install latest Atom deb package
      apt:
        deb: https://atom.io/download/deb

    - name: Install sync-settings apm package
      shell: apm install sync-settings
