---
- name: Xubuntu tweaks and configurations
  tags: xubuntu
  become: yes
  block:

  - name: Remove update notifier
    apt:
      name: update-notifier
      state: absent

  - name: Remove apport to stop annoying bug popups
    apt:
      name: apport
      state: absent
