---
- name: Chrome
  tags: chrome
  become: yes
  block:

  - name: Install google apt signing key
    apt_key:
      url: https://dl-ssl.google.com/linux/linux_signing_key.pub

  - name: Add chrome repository to apt sources
    apt_repository:
      repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
      filename: google-chrome
      update_cache: yes

  - name: Install chrome
    apt:
      name: google-chrome-stable
      state: latest
