---
- name: Tools
  tags: tools
  become: yes
  block:

  - name: ag
    apt:
      name: silversearcher-ag

  - name: bat
    apt:
      deb: https://github.com/sharkdp/bat/releases/download/v0.6.1/bat_0.6.1_amd64.deb
