---
- name: Tools
  tags: tools
  become: yes
  block:

  - name: Install tools with apt
    apt:
      state: latest
      name:
        - curl
        - firefox
        - glances
        - gnome-system-monitor
        - htop
        - redshift-gtk
        - silversearcher-ag
        - tig
        - tree
        - vim

  - name: Install bat
    apt:
      deb: https://github.com/sharkdp/bat/releases/download/v0.6.1/bat_0.6.1_amd64.deb

  - name: Install gotop
    apt:
      deb: https://github.com/cjbassi/gotop/releases/download/2.0.1/gotop_2.0.1_linux_amd64.deb

  - name: Install wrk
    copy:
      src: wrk
      dest: /usr/local/bin/wrk
      mode: 0755

  - name: Install Fira Code font
    copy:
      src: FiraCode-Regular.ttf
      dest: /usr/share/fonts/FiraCode-Regular.ttf
