---
- name: Tools
  tags: tools
  become: yes
  block:

  - name: Install tools with apt
    apt:
      state: latest
      name:
        - curl
        - firefox
        - redshift-gtk
        - silversearcher-ag
        - tig
        - tree
        - vim

  - name: Install bat
    apt:
      deb: https://github.com/sharkdp/bat/releases/download/v0.6.1/bat_0.6.1_amd64.deb
