---
- name: Sublime Text 3
  tags: sublime
  become: yes
  block:

  - name: Install the GPG key
    apt_key:
      url: https://download.sublimetext.com/sublimehq-pub.gpg

  - name: Ensure apt is set up to work with https sources
    apt:
      name: apt-transport-https

  - name: Select the channel to use
    shell: echo "deb https://download.sublimetext.com/ apt/stable/" | tee /etc/apt/sources.list.d/sublime-text.list

  - name: Update apt sources and install Sublime Text
    apt:
      name: sublime-text
      state: latest
      update_cache: yes
