---
- name: Sublime Text
  tags: sublime
  block:

    - name: Install the GPG key
      become: yes
      apt_key:
        url: https://download.sublimetext.com/sublimehq-pub.gpg

    - name: Ensure apt is set up to work with https sources
      become: yes
      apt:
        name: apt-transport-https

    - name: Select the channel to use
      become: yes
      shell: echo "deb https://download.sublimetext.com/ apt/stable/" | tee /etc/apt/sources.list.d/sublime-text.list

    - name: Update apt sources and install Sublime Text
      become: yes
      apt:
        name: sublime-text
        state: latest
        update_cache: yes

    - name: Install Sublime Merge
      become: yes
      apt:
        name: sublime-merge
        state: latest
        update_cache: yes

    - name: Ensure Sublime user packages directory exist
      file:
        path: ~/.config/sublime-text/Packages/User
        state: directory

    - name: Copy user settings
      copy:
        src: settings/{{ item.path }}
        dest: ~/.config/sublime-text/Packages/User/{{ item.path }}
      with_filetree: settings/

    - name: Install fonts
      become: yes
      copy:
        src: fonts/{{ item.path }}
        dest: /usr/share/fonts/{{ item.path }}
      with_filetree: fonts/
