---
- name: Sublime Text 3
  tags: sublime
  block:

  - name: Install the GPG key
    become: yes
    apt_key:
      url: https://download.sublimetext.com/sublimehq-pub.gpg

  - name: Ensure apt is set up to work with https sources
    become: yes
    apt:
      name: apt-transport-https

  - name: Select the channel to use
    become: yes
    shell: echo "deb https://download.sublimetext.com/ apt/stable/" | tee /etc/apt/sources.list.d/sublime-text.list

  - name: Update apt sources and install Sublime Text
    become: yes
    apt:
      name: sublime-text
      state: latest
      update_cache: yes

  - name: Install Sublime Merge
    become: yes
    apt:
      name: sublime-merge
      state: latest
      update_cache: yes

  - name: Ensure Sublime package directories exist
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - ~/.config/sublime-text-3/Installed Packages
      - ~/.config/sublime-text-3/Packages/User

  - name: Install Sublime Package Control
    get_url:
      url: "https://packagecontrol.io/Package Control.sublime-package"
      dest: ~/.config/sublime-text-3/Installed Packages

  - name: Copy Package Control settings file
    copy:
      src: packages.json
      dest: ~/.config/sublime-text-3/Packages/User/Package Control.sublime-settings

  - name: Copy settings file
    copy:
      src: settings.json
      dest: ~/.config/sublime-text-3/Packages/User/Preferences.sublime-settings

  - name: Copy keymap file
    copy:
      src: keymap.json
      dest: ~/.config/sublime-text-3/Packages/User/Default (Linux).sublime-keymap

  - name: Install Fira Code font
    become: yes
    copy:
      src: FiraCode-Regular.ttf
      dest: /usr/share/fonts/FiraCode-Regular.ttf
